---
- name: Configure the server
  hosts: all
  tasks:
    - name: Apply all available system patches
      syspatch:
      register: syspatch

    - name: Reboot if patch requires it
      reboot:
      when: syspatch.reboot_needed

    - name: Set sshd config
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: wheel
        mode: 0644
        validate: '/usr/sbin/sshd -T -f %s'
      notify:
      - restart sshd

    - name: Install nginx
      openbsd_pkg:
        name: nginx

    - name: Copy certs
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/
        owner: root
        group: wheel
        mode: 0600
      with_fileglob:
        - fozzey_ru.*

    - name: Set nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/
        owner: root
        group: wheel
        mode: 0644
      notify:
      - restart nginx

    - name: Upload content
      copy:
        src: html/
        dest: /var/www/html/
        owner: root
        group: daemon
        mode: 0644
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
