name: "Ansible"

defaults:
  run:
    working-directory: ansible

on:
  push:
    branches:
      - master
    paths:
      - ansible/**
      - .github/workflows/ansible.yml

jobs:
  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cert files
        env:
          FOZZEY_RU_CRT: ${{ secrets.FOZZEY_RU_CRT }}
          FOZZEY_RU_KEY: ${{ secrets.FOZZEY_RU_KEY }}
        run: |
          echo "$FOZZEY_RU_CRT" > fozzey_ru.crt
          echo "$FOZZEY_RU_KEY" > fozzey_ru.key
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            fozzey.ru
          known_hosts: |
            fozzey.ru ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJeXcI+WSO1D+wOgc6fRAd9DJkruRegFEBj4afjjYjqO
          options: |
            --user root
