name: "Ansible"

defaults:
  run:
    working-directory: ansible

on:
  push:
    branches:
      - master
    paths:
      - ansible
  workflow_dispatch:

jobs:
  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $SSH_PRIVATE_KEY > ssh_private_key
          mkdir .ssh
          ls .ssh
          echo "fozzey.ru ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOhNKNb3ra00bOWTiC7qu1qA7dBWkKHupnLUGljgkqz+" > ~/.ssh/known_hosts
      - name: Bootstrap ansible
        run: ansible -i fozzey.ru, --key-file ssh_private_key -m raw -a "pkg_add python%3.8" all
      - name: Test Ansible
        run: ansible-playbook -i fozzey.ru, --key-file ssh_private_key main.yml
